#!/usr/bin/perl

use warnings;
use strict;
use Debian::AdduserLogging;

set_msglevel( "error", "warn", "info");

my $message = "this is the message";
log_trace("mtest trace message: %s", "test string");
log_debug("mtest debug message");
log_info("mtest info message");
log_warn("mtest warn message");
log_err("mtest err message: %s postmessage", $message);
log_fatal("mtest fatal message");

